instance_id                        = "i-056886ca1d1e4c916"
cpu_utilization_period             = "300"
cpu_utilization_threshold          = "0.2"
cpu_utilization_evaluation_periods = "3"
network_in_threshold               = "1000"
network_packets_threshold          = "15"
